providers = ["python", "node"]

[phases.setup]
nixPkgs = ["python3", "python3Packages.pip", "ffmpeg", "..."]

[phases.install]
cmds = ["pip install -r requirements.txt", "npm install"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "python3 main.py"
